{% set name = "hybgensea" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/hybgensea-{{ version }}.tar.gz
  sha256: 757705144474ef4811722ba08213143bb3ccb42ee4887d24279a56c4c5f9c25a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python
    - scikit-build-core
    - nanobind
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - hybgensea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdealencar/PyHygese
  summary: Wrapper for the Hybrid Genetic Search algorithm for Capacitated Vehicle Routing Problems (HGS-CVRP)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdealencar
    - simutisernestas
